"""
Tests each trained model's day-3 prediction against the mock flood event's
ground truth (ml/mock_flood_event.py) - a genuine out-of-formula test,
since the ground truth was generated by a different rule (threshold/OR)
and a different random seed than the model's own training heuristic
(train_risk_model.py's smooth weighted sum, seed 7 vs. this event's seed 99).

Critically, the model is only given the day-3 instantaneous rainfall
reading (~73mm at the day-3 burst peak) - NOT the cumulative 3-day
exposure the ground truth was generated from. A model that only memorized
the training formula would have no reason to correctly anticipate outcomes
driven by an input it never sees; agreement here reflects the real
drainage/incident-proximity features actually carrying signal.

Also measures DRF dispatch quality: of the (fleet-size-limited) vehicles
the live system would send to the highest-priority predicted cells, how
many actually match the mock ground truth's flooded set (dispatch
precision), and what share of all actually-flooded cells a 10-vehicle
fleet can realistically cover (coverage).

Run: python validate_against_mock_event.py
Output: data/processed/mock_event_validation_results.json
"""
import json

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from common import DATA_PROCESSED, FEATURES_CSV_PATH, MODEL_NAMES, MODEL_PATHS

GROUND_TRUTH_PATH = f"{DATA_PROCESSED}/mock_flood_event_ground_truth.csv"
META_PATH = f"{DATA_PROCESSED}/mock_flood_event_meta.json"
RESULTS_PATH = f"{DATA_PROCESSED}/mock_event_validation_results.json"

FLEET_SIZE = 10  # matches backend/data/processed/drf_depots.json (2 vehicles x 5 GHMC zones)
PREDICTED_RED_FRACTION = 0.20  # matches the production percentile band_method's top-20% = red


def main():
    with open(META_PATH, encoding="utf-8") as f:
        meta = json.load(f)
    ground_truth = pd.read_csv(GROUND_TRUTH_PATH)
    features_df = pd.read_csv(FEATURES_CSV_PATH)

    day3_rainfall_mm = meta["day3_peak_rainfall_mm"]
    df = features_df.merge(ground_truth[["cell_id", "actual_flooded"]], on="cell_id")
    df["rainfall_mm"] = day3_rainfall_mm

    results = {"event": meta, "models": {}}

    for name in MODEL_NAMES:
        bundle = joblib.load(MODEL_PATHS[name])
        model, feature_cols = bundle["model"], bundle["feature_cols"]
        risk_score = model.predict(df[feature_cols]).clip(0, 1)

        # Same rule the live dashboard uses for "red" at the percentile band method.
        red_threshold = np.quantile(risk_score, 1 - PREDICTED_RED_FRACTION)
        predicted_flooded = (risk_score >= red_threshold).astype(int)
        actual = df["actual_flooded"].values

        mobilization_score = risk_score * df["population_density"].values
        dispatch_order = np.argsort(-mobilization_score)
        dispatched_idx = [i for i in dispatch_order if predicted_flooded[i] == 1][:FLEET_SIZE]
        dispatch_hits = int(actual[dispatched_idx].sum())

        results["models"][name] = {
            "day3_test_rainfall_mm": round(float(day3_rainfall_mm), 1),
            "predicted_flooded_count": int(predicted_flooded.sum()),
            "accuracy": round(float(accuracy_score(actual, predicted_flooded)), 4),
            "precision": round(float(precision_score(actual, predicted_flooded, zero_division=0)), 4),
            "recall": round(float(recall_score(actual, predicted_flooded, zero_division=0)), 4),
            "f1_score": round(float(f1_score(actual, predicted_flooded, zero_division=0)), 4),
            "drf_dispatch_precision": round(dispatch_hits / len(dispatched_idx), 4) if dispatched_idx else 0.0,
            "drf_coverage_of_actual_flooding": round(dispatch_hits / int(actual.sum()), 4) if actual.sum() else 0.0,
            "drf_vehicles_dispatched": len(dispatched_idx),
            "drf_correct_dispatches": dispatch_hits,
        }

    with open(RESULTS_PATH, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    print(f"Mock event: {meta['cumulative_rainfall_mm']}mm cumulative, day-3 test rainfall {day3_rainfall_mm:.1f}mm")
    print(f"Actually flooded: {meta['actual_flooded_count']}/{meta['total_cells']} cells\n")
    for name, m in results["models"].items():
        print(
            f"[{name}] acc={m['accuracy']:.3f} precision={m['precision']:.3f} recall={m['recall']:.3f} "
            f"f1={m['f1_score']:.3f} | DRF: {m['drf_correct_dispatches']}/{m['drf_vehicles_dispatched']} dispatches "
            f"correct ({m['drf_dispatch_precision']:.0%}), covers {m['drf_coverage_of_actual_flooding']:.1%} of actual flooding"
        )
    print(f"\nSaved -> {RESULTS_PATH}")


if __name__ == "__main__":
    main()
