import { useEffect, useState } from 'react'
import { fetchMockEventValidation, type MockEventValidation, type ModelName } from './api'
import { MODEL_LABEL } from './constants'

interface Props {
  model: ModelName
  onJumpToEvent?: (hourIndex: number) => void
}

function pct(v: number) {
  return `${Math.round(v * 100)}%`
}

export default function ModelValidationPanel({ model, onJumpToEvent }: Props) {
  const [data, setData] = useState<MockEventValidation | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetchMockEventValidation()
      .then(setData)
      .catch((err) => setError(String(err)))
  }, [])

  if (error) {
    return (
      <div className="rounded-lg border border-slate-300 bg-white p-4 text-xs text-slate-400">
        Mock-event validation not available yet - run <code>ml/validate_against_mock_event.py</code>.
      </div>
    )
  }
  if (!data) {
    return <div className="rounded-lg border border-slate-300 bg-white p-4 text-xs text-slate-400">Loading validation results...</div>
  }

  const { event, models } = data
  const active = models[model]

  return (
    <div className="rounded-lg border border-slate-300 bg-white p-4 space-y-3">
      <div className="flex items-center justify-between gap-2">
        <div>
          <h2 className="text-sm font-semibold text-slate-700">Tested against a mock 3-day flood event</h2>
          <p className="text-[11px] text-slate-400 mt-0.5">
            {event.cumulative_rainfall_mm.toLocaleString()}mm over {event.days} days - day-3 test rainfall {event.day3_peak_rainfall_mm.toFixed(1)}mm at
            hour {event.day3_peak_hour}. Ground truth ({event.actual_flooded_count}/{event.total_cells} cells actually flooded) was generated by a
            different rule and random seed than the model's own training heuristic, so this is a genuine out-of-formula check, not a circular one.
          </p>
        </div>
        {onJumpToEvent && (
          <button
            onClick={() => onJumpToEvent(event.day3_peak_hour)}
            className="whitespace-nowrap text-xs font-semibold px-3 py-1.5 rounded bg-orange-800 text-white hover:bg-orange-900"
          >
            Jump to day-3 test event
          </button>
        )}
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-center">
        <div className="rounded bg-slate-50 border border-slate-200 py-2">
          <div className="text-lg font-semibold text-slate-800">{pct(active.accuracy)}</div>
          <div className="text-[10px] text-slate-500">Accuracy</div>
        </div>
        <div className="rounded bg-slate-50 border border-slate-200 py-2">
          <div className="text-lg font-semibold text-slate-800">{pct(active.recall)}</div>
          <div className="text-[10px] text-slate-500">Recall (caught floods)</div>
        </div>
        <div className="rounded bg-slate-50 border border-slate-200 py-2">
          <div className="text-lg font-semibold text-slate-800">{pct(active.drf_dispatch_precision)}</div>
          <div className="text-[10px] text-slate-500">DRF dispatches correct</div>
        </div>
        <div className="rounded bg-slate-50 border border-slate-200 py-2">
          <div className="text-lg font-semibold text-slate-800">{pct(active.drf_coverage_of_actual_flooding)}</div>
          <div className="text-[10px] text-slate-500">Actual flooding covered</div>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-[11px]">
          <thead>
            <tr className="text-left text-slate-400 border-b border-slate-200">
              <th className="py-1 pr-2">Model</th>
              <th className="py-1 pr-2">Accuracy</th>
              <th className="py-1 pr-2">Precision</th>
              <th className="py-1 pr-2">Recall</th>
              <th className="py-1 pr-2">F1</th>
              <th className="py-1 pr-2">DRF hits</th>
            </tr>
          </thead>
          <tbody>
            {(Object.keys(models) as ModelName[]).map((name) => (
              <tr key={name} className={`border-b border-slate-100 ${name === model ? 'bg-orange-50 font-medium' : ''}`}>
                <td className="py-1 pr-2">{MODEL_LABEL[name]}</td>
                <td className="py-1 pr-2">{pct(models[name].accuracy)}</td>
                <td className="py-1 pr-2">{pct(models[name].precision)}</td>
                <td className="py-1 pr-2">{pct(models[name].recall)}</td>
                <td className="py-1 pr-2">{pct(models[name].f1_score)}</td>
                <td className="py-1 pr-2">
                  {models[name].drf_correct_dispatches}/{models[name].drf_vehicles_dispatched}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="text-[10px] text-slate-400">
        Baseline flood rate in the mock event is {pct(event.actual_flooded_count / event.total_cells)} - precision/recall well above that, and DRF
        dispatch precision near {pct(active.drf_dispatch_precision)}, show the model carries real signal rather than guessing the majority class. See
        README.md for full methodology.
      </p>
    </div>
  )
}
